# Generated by Django 6.0.3 on 2026-04-12 16:00

from django.db import migrations, models


def renumber_gig_photo_sort_orders(apps, schema_editor):
    """Normalize existing gig photo sort values to 0-based increments."""
    GigPhoto = apps.get_model("main_site", "GigPhoto")
    for index, photo in enumerate(GigPhoto.objects.order_by("sort_order", "id")):
        if photo.sort_order != index:
            photo.sort_order = index
            photo.save(update_fields=["sort_order"])


def seed_album_art_and_animation_assets(apps, schema_editor):
    """Seed the new artwork tables from the site's current static gallery."""
    AlbumArt = apps.get_model("main_site", "AlbumArt")
    AnimationAsset = apps.get_model("main_site", "AnimationAsset")

    if AlbumArt.objects.exists() or AnimationAsset.objects.exists():
        return

    AlbumArt.objects.bulk_create(
        [
            AlbumArt(
                title="Dark and Light - Artist Cover",
                image_path="images/album_art/dark_and_light_artist_cover.jpg",
                alt_text="Dark and Light artist cover artwork",
                featured=True,
                sort_order=0,
                is_active=True,
            ),
            AlbumArt(
                title="Dark and Light - Instrumental Artwork",
                image_path="images/album_art/dark_and_light_instrumental.jpg",
                alt_text="Dark and Light instrumental artwork",
                featured=True,
                sort_order=1,
                is_active=True,
            ),
            AlbumArt(
                title="Current Artist Profile",
                image_path="images/album_art/Current_artist_profile_picture.jpg",
                alt_text="Current artist profile portrait",
                featured=False,
                sort_order=2,
                is_active=True,
            ),
        ]
    )
    AnimationAsset.objects.bulk_create(
        [
            AnimationAsset(
                title="Symbol Animation",
                media_kind="image",
                file_path="images/album_art/symbol_animation.gif",
                alt_text="Symbol animation artwork",
                featured=False,
                fit_contain=False,
                sort_order=3,
                is_active=True,
            ),
            AnimationAsset(
                title="Buddlea Animation",
                media_kind="image",
                file_path="images/album_art/buddlea_animation.gif",
                alt_text="Buddlea animation artwork",
                featured=False,
                fit_contain=True,
                sort_order=4,
                is_active=True,
            ),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("main_site", "0002_normalize_gig_photo_titles"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumArt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=140)),
                ("alt_text", models.CharField(blank=True, max_length=180)),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Lower numbers appear earlier on the page.")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "image_path",
                    models.CharField(
                        blank=True,
                        help_text="Optional path relative to static/, for example images/album_art/cover.jpg.",
                        max_length=255,
                    ),
                ),
                (
                    "image_file",
                    models.FileField(
                        blank=True,
                        help_text="Optional file upload for this album artwork.",
                        upload_to="album_art/uploads/",
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("fit_contain", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Album art",
                "verbose_name_plural": "Album art",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="AnimationAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=140)),
                ("alt_text", models.CharField(blank=True, max_length=180)),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Lower numbers appear earlier on the page.")),
                ("is_active", models.BooleanField(default=True)),
                ("media_kind", models.CharField(choices=[("image", "Image / GIF"), ("video", "Video")], default="image", max_length=10)),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Optional path relative to static/, for example images/album_art/animation.gif.",
                        max_length=255,
                    ),
                ),
                (
                    "file_upload",
                    models.FileField(
                        blank=True,
                        help_text="Optional upload for the animation file.",
                        upload_to="animations/uploads/",
                    ),
                ),
                (
                    "poster_path",
                    models.CharField(blank=True, help_text="Optional poster path for video animations.", max_length=255),
                ),
                (
                    "poster_upload",
                    models.FileField(
                        blank=True,
                        help_text="Optional poster upload for video animations.",
                        upload_to="animations/posters/",
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("fit_contain", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Animation",
                "verbose_name_plural": "Animations",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.AlterModelOptions(
            name="gigphoto",
            options={"ordering": ("sort_order", "id"), "verbose_name": "Gig photo", "verbose_name_plural": "Gig photos"},
        ),
        migrations.AddField(
            model_name="gigphoto",
            name="image_file",
            field=models.FileField(
                blank=True,
                help_text="Optional file upload for the main gig photo.",
                upload_to="gig_photos/uploads/",
            ),
        ),
        migrations.AddField(
            model_name="gigphoto",
            name="thumbnail_file",
            field=models.FileField(
                blank=True,
                help_text="Optional thumbnail upload. Falls back to the main image when blank.",
                upload_to="gig_photos/thumbs/uploads/",
            ),
        ),
        migrations.AlterField(
            model_name="gigphoto",
            name="image_path",
            field=models.CharField(
                blank=True,
                help_text="Optional path relative to static/, for example images/gig_photos/photo.jpeg.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="gigphoto",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, help_text="Lower numbers appear earlier on the page."),
        ),
        migrations.AlterField(
            model_name="gigphoto",
            name="thumbnail_path",
            field=models.CharField(
                blank=True,
                help_text="Optional static thumbnail path. Falls back to the main image when blank.",
                max_length=255,
            ),
        ),
        migrations.RunPython(renumber_gig_photo_sort_orders, migrations.RunPython.noop),
        migrations.RunPython(seed_album_art_and_animation_assets, migrations.RunPython.noop),
    ]
