# Generated by Django 6.0.3 on 2026-04-12 19:01

from django.db import migrations, models


def seed_header_and_nav_items(apps, schema_editor):
    """Seed the new site-structure tables from the current live content."""
    HeaderSocialLink = apps.get_model("main_site", "HeaderSocialLink")
    PrimaryNavItem = apps.get_model("main_site", "PrimaryNavItem")

    if not HeaderSocialLink.objects.exists():
        HeaderSocialLink.objects.bulk_create(
            [
                HeaderSocialLink(
                    label="Bandcamp",
                    href="https://josephlovesjohn.bandcamp.com",
                    icon_class="icon brands fa-bandcamp",
                    sort_order=0,
                    is_active=True,
                ),
                HeaderSocialLink(
                    label="Instagram",
                    href="https://www.instagram.com/josephlovesjohn_music/",
                    icon_class="icon brands fa-instagram",
                    sort_order=1,
                    is_active=True,
                ),
                HeaderSocialLink(
                    label="YouTube",
                    href="https://www.youtube.com/@JosephlovesJohn",
                    icon_class="icon brands fa-youtube",
                    sort_order=2,
                    is_active=True,
                ),
                HeaderSocialLink(
                    label="Amazon Music",
                    href="https://music.amazon.co.uk/artists/B0GHXDGN9M/josephlovesjohn",
                    icon_class="icon brands fa-amazon",
                    sort_order=3,
                    is_active=True,
                ),
                HeaderSocialLink(
                    label="Apple Music",
                    href="https://music.apple.com/us/artist/josephlovesjohn/1869723292",
                    icon_class="icon brands fa-apple",
                    sort_order=4,
                    is_active=True,
                ),
                HeaderSocialLink(
                    label="TikTok",
                    href="https://www.tiktok.com/@joseph_loves_john",
                    icon_class="icon brands fa-tiktok",
                    sort_order=5,
                    is_active=True,
                ),
            ]
        )

    if not PrimaryNavItem.objects.exists():
        PrimaryNavItem.objects.bulk_create(
            [
                PrimaryNavItem(label="Intro", href="#intro", sort_order=0, is_active=True),
                PrimaryNavItem(label="Music", href="#music", sort_order=1, is_active=True),
                PrimaryNavItem(label="Art", href="#art", sort_order=2, is_active=True),
                PrimaryNavItem(label="Contact", href="#contact", sort_order=3, is_active=True),
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("main_site", "0003_albumart_animationasset_alter_gigphoto_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeaderSocialLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Lower numbers appear earlier on the page.")),
                ("is_active", models.BooleanField(default=True)),
                ("label", models.CharField(max_length=80)),
                ("href", models.URLField(max_length=255)),
                ("icon_class", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Header social link",
                "verbose_name_plural": "Header social links",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="PrimaryNavItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Lower numbers appear earlier on the page.")),
                ("is_active", models.BooleanField(default=True)),
                ("label", models.CharField(max_length=80)),
                ("href", models.CharField(help_text="For example #intro or #music.", max_length=120)),
            ],
            options={
                "verbose_name": "Primary nav item",
                "verbose_name_plural": "Primary nav items",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.RunPython(seed_header_and_nav_items, migrations.RunPython.noop),
    ]
