# Generated by Django 6.0.3 on 2026-04-13 00:00

from django.db import migrations


def add_spotify_social_link(apps, schema_editor):
    """Ensure the seeded social links include Spotify in the preferred slot."""
    HeaderSocialLink = apps.get_model("main_site", "HeaderSocialLink")

    spotify_link, _created = HeaderSocialLink.objects.get_or_create(
        label="Spotify",
        defaults={
            "href": "https://open.spotify.com/artist/27YZiLsfuwfBI5e4BZyTIi?si=rcYZFzPzSPCfartpPGM6gg",
            "icon_class": "icon brands fa-spotify",
            "sort_order": 1,
            "is_active": True,
        },
    )

    spotify_link.href = "https://open.spotify.com/artist/27YZiLsfuwfBI5e4BZyTIi?si=rcYZFzPzSPCfartpPGM6gg"
    spotify_link.icon_class = "icon brands fa-spotify"
    spotify_link.sort_order = 1
    spotify_link.is_active = True
    spotify_link.save(update_fields=["href", "icon_class", "sort_order", "is_active"])

    preferred_order = {
        "Bandcamp": 0,
        "Instagram": 2,
        "YouTube": 3,
        "Amazon Music": 4,
        "Apple Music": 5,
        "TikTok": 6,
    }

    for label, sort_order in preferred_order.items():
        HeaderSocialLink.objects.filter(label=label).update(sort_order=sort_order)


class Migration(migrations.Migration):

    dependencies = [
        ("main_site", "0004_headersociallink_primarynavitem"),
    ]

    operations = [
        migrations.RunPython(add_spotify_social_link, migrations.RunPython.noop),
    ]
