# Generated by Django 6.0.3 on 2026-04-11 20:23

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('artist_name', models.CharField(default='JosephlovesJohn and Jayne Connell', max_length=180)),
                ('meta', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('art_path', models.CharField(max_length=255)),
                ('art_alt', models.CharField(blank=True, max_length=180)),
                ('preview_file_wav', models.CharField(blank=True, max_length=255)),
                ('preview_file_mp3', models.CharField(blank=True, max_length=255)),
                ('download_file_path', models.CharField(max_length=255)),
                ('product_kind', models.CharField(choices=[('single', 'Single'), ('bundle', 'Bundle'), ('album', 'Album')], default='single', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('2.99'), max_digits=6)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=180)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed')], default='confirmed', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_snapshot', models.CharField(max_length=180)),
                ('artist_snapshot', models.CharField(max_length=180)),
                ('meta_snapshot', models.CharField(blank=True, max_length=120)),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=6)),
                ('art_path_snapshot', models.CharField(max_length=255)),
                ('art_alt_snapshot', models.CharField(blank=True, max_length=180)),
                ('download_file_path', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product')),
            ],
        ),
    ]
