# Generated by Django 6.0.4 on 2026-06-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_customerprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='download_file_wav_path',
        ),
        migrations.RemoveField(
            model_name='product',
            name='download_file_wav_path',
        ),
        migrations.RemoveField(
            model_name='product',
            name='preview_file_wav',
        ),
    ]
